### ISSUE TITLE
Linking places

### ISSUE THREAD

**Issue by cutic** [Thaerious/NERVE#48]
1. Errors when linking to places:

- these errors appeared on both PC and Mac in both Firefox and Chrome when trying to link places or Customize link

- documents used for testing: Cultural Mapping - Mapping Tags and Tagging Maps, Where are you from? 

![error place](https://cloud.githubusercontent.com/assets/17013268/14972007/3d220ff4-1095-11e6-825f-892fa30b72b1.jpg)

![error place2](https://cloud.githubusercontent.com/assets/17013268/14972008/3f6c5274-1095-11e6-8001-caa8aec2a6af.jpg)

![json error](https://cloud.githubusercontent.com/assets/17013268/14972010/465cd87e-1095-11e6-871b-2a5cd328adeb.jpg)

2. I don’t always get any options when trying to link a place right away on PC. Several minutes later several errors popped up as well as the options box. Seems to work fine on Mac in both browsers.

![place error](https://cloud.githubusercontent.com/assets/17013268/14972054/d0d2a8bc-1095-11e6-882e-0db455f942fc.jpg)

3. VIAF had disappeared from lookups on both PC and Mac in both browsers.

**Comment by Thaerious** [comment]
VIAF has started acting funny, no change in code has occurred.  I'll be looking at this today.

**Comment by SusanBrown** [comment]
I wasn’t able to get VIAF lookup at all—that is, no VIAF matches were offered--when I was using it the last couple of times.

**Comment by Thaerious** [comment]
Viaf has been fixed.  Reopen if the problem re-emerges.

**Comment by abramoffcwrc** [comment]
When I double clicked on 96 West Street, I got this error. (Found in debugCase1 on PC in Firefox and Chrome).

![image](https://cloud.githubusercontent.com/assets/17013275/15027533/96c2b280-1201-11e6-80f1-6f2723dc217b.png)
Linking places still doesn't work. We get the same error we used to get.

**Comment by cutic** [comment]
Errors when linking places appear randomly on both PC and Mac and in both browsers. It feels vary random because at certain moments it works really well and you're able to link places, but then it randomly stops working and gives you various errors (screenshots above).

**Comment by Thaerious** [comment]
It's not random,  it's just unknown, which is why these sometimes take awhile.  This is the same as another ticket, so I'm going to close it.
